# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import random
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML

# Extended the style options

styles= {
    "Impressionism": {
        "themes": ["light and color", "fleeting moments", "nature"],
        "technique": "short brush strokes; painting en plein air; capturing changing light",
        "colors": "soft pastels, pale yellows, sky blues",
        "examples": ["Impression, Sunrise"],
        "artists": ["Claude Monet", "Pierre-Auguste Renoir"]
    },
    "Cubism": {
        "themes": ["geometry", "fragmentation", "perspective"],
        "technique": "multiple viewpoints; abstracted objects; flat space",
        "colors": "earth tones, muted greys, shades of blue",
        "examples": ["Les Demoiselles d'Avignon"],
        "artists": ["Pablo Picasso", "Georges Braque"]
    },
    "Surrealism": {
        "themes": ["dreams", "the unconscious", "irrational worlds"],
        "technique": "unexpected juxtapositions; precise detail; dreamlike composition",
        "colors": "symbolic reds, midnight blues, bright contrasts",
        "examples": ["The Persistence of Memory"],
        "artists": ["Salvador Dalí", "René Magritte"]
    },
    "Expressionism": {
        "themes": ["emotion", "introspection", "spiritual crisis"],
        "technique": "bold brushwork; exaggerated forms; vivid colors",
        "colors": "intense reds, dark purples, stark blacks",
        "examples": ["The Scream"],
        "artists": ["Edvard Munch", "Egon Schiele"]
    },
    "Minimalism": {
        "themes": ["simplicity", "reduction", "order"],
        "technique": "clean lines; limited elements; geometric compositions",
        "colors": "monochrome, white space, muted tones",
        "examples": ["Untitled (Stacks)"],
        "artists": ["Donald Judd", "Agnes Martin"]
    },
    "Fauvism": {
        "themes": ["wild color", "joy of life", "spontaneity"],
        "technique": "vibrant brushstrokes; unblended color; simplified forms",
        "colors": "bright oranges, greens, and electric blues",
        "examples": ["Woman with a Hat"],
        "artists": ["Henri Matisse", "André Derain"]
    },
    "Abstract Expressionism": {
        "themes": ["freedom", "inner chaos", "gesture"],
        "technique": "dripping paint; energetic strokes; scale and emotion",
        "colors": "dramatic contrasts, primary colors, dynamic blacks",
        "examples": ["No. 5, 1948"],
        "artists": ["Jackson Pollock", "Mark Rothko"]
    },
    "Pop Art": {
        "themes": ["mass culture", "consumerism", "irony"],
        "technique": "bold outlines; flat colors; printmaking aesthetics",
        "colors": "comic-style primaries, neon tones",
        "examples": ["Marilyn Diptych"],
        "artists": ["Andy Warhol", "Roy Lichtenstein"]
    }
}

def generate_inspiration(style_name):
  data = styles[style_name]
  theme = random.choice(data["themes"])
  idea = f"A painting expressing '{theme}' in the {style_name} style."

  return {
      "idea": idea,
      "technique": random.choice(data["technique"].split(";")).strip(),
      "colors": data["colors"],
      "example": random.choice(data["examples"]),
      "artist": random.choice(data["artists"])

}

def art_inspiration_ui():
  clear_output()
  display(HTML("<h2>🎨 Get Inspired by an Art Style</h2>"))

  style_dropdown = widgets.Dropdown(
      options=sorted(styles.keys()),
      description="Art Style:"

  )

  generate_button = widgets.Button(
      description="Generate Inspiration",
      button_style="success",
      icon="lightbulb-o"
  )

  output_box = widgets.Output()

  def on_generate_clicked(b):
    with output_box:
      clear_output()
      inspiration = generate_inspiration(style_dropdown.value)
      print(f"🖌️ Idea: {inspiration['idea']}")
      print(f"💡 Technique Tip: {inspiration['technique']}")
      print(f"🎨 Suggested Colors: {inspiration['colors']}")
      print(f"🧑‍🎨 Artist to Explore: {inspiration['artist']}")
      print(f"🖼️ Example Work: {inspiration['example']}")


  generate_button.on_click(on_generate_clicked)
  display(widgets.VBox([style_dropdown, generate_button, output_box]))

art_inspiration_ui()